spring.application.name=TC1

# Datasource com fallbacks para desenvolvimento local
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tc1}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=${SPRING_FLYWAY_ENABLED:true}
spring.flyway.url=${spring.datasource.url}
spring.flyway.user=${spring.datasource.username}
spring.flyway.password=${spring.datasource.password}

# Security
security.jwt.secret=${JWT_SECRET:RiU72a2gVE6ijWmVl6ySe5nb6uy1tHTnESgvWmYsX2I=}
security.jwt.expiration=${JWT_EXPIRATION:3600000}