CREATE TABLE users (
    tipo VARCHAR(31) NOT NULL,
    id UUID NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    login VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP,
    updated_by VARCHAR(255),
    end_logradouro VARCHAR(255),
    end_numero VARCHAR(255),
    end_complemento VARCHAR(255),
    end_bairro VARCHAR(255),
    end_cidade VARCHAR(255),
    end_uf VARCHAR(2),
    end_cep VARCHAR(8),
    cpf VARCHAR(11),
    cnpj VARCHAR(14),
    PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT uq_users_login UNIQUE (login)
);